#!/bin/sh

set -e

if type -p java; then
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    _java="$JAVA_HOME/bin/java"
else
    echo 'could not find Java Runtime Environment (JRE)'
    exit
fi

if type -p javac; then
    _javac=javac
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/javac" ]];  then
    _javac="$JAVA_HOME/bin/javac"
else
    echo 'could not find Java Development Kit (JDK).'
    exit
fi

if [[ "$_javac" ]]; then
    javac_ver=$("$_javac" -version 2>&1 | awk '/javac/ {print $2}')
    echo javac version "$javac_ver"
    if [[ ! "$javac_ver" > "1.8.0" ]]; then
        echo 'you need JDK 1.8 or later to build this software.'
        exit
    fi
fi

if [[ "$_java" ]]; then
    java_ver=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo java version "$java_ver"
    if [[ ! "$java_ver" > "1.8.0" ]]; then
        echo 'you need JRE 1.8 or later to run this software.'
        exit
    fi
fi

rm -rf build
mkdir -p ./build
cd src
javac -d ../build Remologue.java -Xlint
cd ../build
jar cvfe Remologue.jar Remologue .
cp -R ../resources .
zip -ur Remologue.jar resources
cd ..
cp .remologue ~/
java -jar build/Remologue.jar

